### ISSUE TITLE
bug: 官网无法访问 https://flyonui.com

### ISSUE THREAD

**Issue by overlookart** [themeselection/flyonui#13]
### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://flyonui.com

### Describe your issue

Cancelled load to https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=495768&theme=light because it violates the resource's Cross-Origin-Resource-Policy response header.

Failed to load resource: Cancelled load to https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=495768&theme=light because it violates the resource's Cross-Origin-Resource-Policy response header.

Failed to load resource: 发生SSL错误，无法建立到该服务器的安全连接。

Failed to load resource: 请求超时。

**Comment by ajaypatelaj** [comment]
Hello @overlookart ,

Thanks for sharing your input.

The error regarding “Cross-Origin-Resource-Policy response header” indicates a CORS (Cross-Origin Resource Sharing) issue. This happens when a resource (like the widget from api.producthunt.com) is blocked from being loaded due to cross-origin security policies. To resolve this:

- Check the CORS settings on the external service (https://api.producthunt.com). It’s possible that the ProductHunt API is not configured to allow loading of its resources from flyonui.com.
- Use a proxy or host the resource locally: As a workaround, you could fetch the image or asset server-side and serve it from your own server to avoid CORS restrictions.

Could you please share a screenshot of how the webpage looks line in the browser?
Also, consider sharing the browser developer tools console tab screenshot.

**Comment by PruthviPraj00** [comment]
Hello @overlookart 

I am closing this ticket. Feel free to reopen it or create a new one if you encounter further issues.
