### ISSUE TITLE
bug: outline class not working

### ISSUE THREAD

**Issue by michaelcozzolino** [themeselection/flyonui#20]
### What version of FlyonUI are you using?

1.1.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://github.com/michaelcozzolino/flyonui-outline-bug

### Describe your issue

if i use the outline class of a button
    `<button class="btn btn-outline btn-primary">primary</button>`
the class does not work
i get the following buttons:
![image](https://github.com/user-attachments/assets/bcff659e-8902-4948-ac70-5a04f6cf2529)

if i add the class border-solid it works.
for other elements that have the outline class it works without adding any further class.
the bug happens because the elements have no "border-style: solid" in the css and the fix would just to add "border-solid" to the @apply of .btn in src/components/styled/button.css, but also to the other elements as, according to the docs
https://developer.mozilla.org/en-US/docs/Web/CSS/border

`The border will be invisible if its style is not defined. This is because the style defaults to none.`

you can check the repo that i have given.
just run
`yarn install`
`yarn docs:dev`

and go to http://localhost:5173/markdown-examples.html

i think in the flyonui docs it works because probably the border-style: solid css is inherited from some parent elements.
if the bug is confirmed would it be ok for me to fix it?

**Comment by yagnikvamja** [comment]
Hello @michaelcozzolino ,

_i think in the flyonui docs it works because probably the border-style: solid css is inherited from some parent elements.
if the bug is confirmed would it be ok for me to fix it?_

- As `border-style: solid` is applied by default in Tailwind CSS, so we did not include it explicitly in the FlyonUI button styles, as there is no need to override an already applied style.

However, VitePress applies `border: 0` to buttons, which removes the border’s style, color, and width entirely. While FlyonUI successfully applies the border color and width, we didn't explicitly set `border-style` because it is applied by default in Tailwind CSS. This lack of an explicit `border-style` allows VitePress’s `border: 0` to take precedence, resulting in this issue. This behavior appears to be specific to VitePress, as the button displays correctly in other frameworks.

For now, please continue using the same approach, we'll make updates in a future release.

Best regards,
