### ISSUE TITLE
docs: select-filled-focused class

### ISSUE THREAD

**Issue by michaelcozzolino** [themeselection/flyonui#32]
### On which page do you see this issue?

https://flyonui.com/docs/forms/select/#filled-select

### Describe the issue

i wonder what is the purpose of the `select-filled-focused` class, i tried to remove it for the filled select component and had no difference.

### What browsers are you seeing the problem on?

Chrome

**Comment by yagnikvamja** [comment]
Hello @michaelcozzolino ,

Thank you for your feedback.

The purpose of the `select-filled-focused` class is to create a bottom horizontal line to visually indicate when the input is active. The issue you mentioned, where the difference isn't noticeable, because the overlay occur for selecting options which makes the line unclear, reducing its visibility.

To observe the filled-focused class functionality more clearly, I recommend referring to **Input** example provided in the [FlyonUI - Input](https://flyonui.com/docs/forms/input/#filled-label). Additionally, try removing the `input-filled-focused` class. This should help demonstrate the behavior more distinctly.

I hope this explanation addresses your concern. Please feel free to reach out if you have further questions.

~Best regards,

**Comment by michaelcozzolino** [comment]
understood! thanks for your explanation!
